/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kafka

import org.jsmart.zerocode.core.domain.Scenario
import org.jsmart.zerocode.core.domain.TargetEnv
import org.jsmart.zerocode.core.runner.ZeroCodeUnitRunner
import org.junit.runner.RunWith
import org.junit.Test as JUnit4Test

@TargetEnv("kafka_servers/host.properties")
@RunWith(ZeroCodeUnitRunner::class)
class ProducerTest {

    @JUnit4Test
    @Scenario("scenario/produce_record.json")
    fun `test produce record`() {
    }
}

